apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - namespace.yaml
  - statefulset.yaml
  - secret.yaml
  - service.yaml

configMapGenerator:
  - name: postgres
    files:
      - config/pg_hba.conf
      - config/postgres.conf

generatorOptions:
  disableNameSuffixHash: true