apiVersion: postgres.kubepost.io/v1alpha1
kind: Role
metadata:
  name: kubepost
  namespace: default
spec:
  instanceSelector:
    matchLabels:
      instance: kubepost
  instanceNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  cascadeDelete: false
  grants:
    - database: kubepost
      objects:
        - identifier: public
          privileges:
            - ALL
          schema: public
          type: SCHEMA
          withGrantOption: true
        - identifier: test
          privileges:
            - ALL
          schema: public
          table: example
          type: TABLE
          withGrantOption: true
  options:
    - SUPERUSER
  preventDeletion: false
