apiVersion: postgres.kubepost.io/v1alpha1
kind: Connection
metadata:
  name: kubepost
  labels:
    instance: default
spec:
  host: localhost
  port: 5432
  database: postgres
  username:
    name: kubepost
    key: username
  password:
    name: kubepost
    key: password
