apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: kubepost-instance-controller
spec:
  resources:
    - apiVersion: kubepost.io/v1alpha1
      resource: instances
  resyncPeriodSeconds: 5
  hooks:
    sync:
      webhook:
        url: http://kubepost-controller.metacontroller/instance/sync
    customize:
      webhook:
        url: http://kubepost-controller.metacontroller/instance/customize
    finalize:
      webhook:
        url: http://kubepost-controller.metacontroller/instance/sync
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: kubepost-role-controller
spec:
  resources:
    - apiVersion: kubepost.io/v1alpha1
      resource: roles
  resyncPeriodSeconds: 5
  hooks:
    sync:
      webhook:
        url: http://kubepost-controller.metacontroller/role/sync
    customize:
      webhook:
        url: http://kubepost-controller.metacontroller/role/customize
    finalize:
      webhook:
        url: http://kubepost-controller.metacontroller/role/sync
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: kubepost-database-controller
spec:
  resources:
    - apiVersion: kubepost.io/v1alpha1
      resource: databases
  resyncPeriodSeconds: 5
  hooks:
    sync:
      webhook:
        url: http://kubepost-controller.metacontroller/database/sync
    customize:
      webhook:
        url: http://kubepost-controller.metacontroller/database/customize
    finalize:
      webhook:
        url: http://kubepost-controller.metacontroller/database/sync
