---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.kubepost.io
  resources:
  - connections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.kubepost.io
  resources:
  - connections/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.kubepost.io
  resources:
  - connections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgres.kubepost.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.kubepost.io
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.kubepost.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgres.kubepost.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.kubepost.io
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.kubepost.io
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
