apiVersion: kubepost.io/v1alpha1
kind: Instance
metadata:
  name: kubepost
spec:
  host: localhost
  port: 5432
  database: postgres
  secretRef:
    name: kubepost-instance-credentials
    namespace: default
    userKey: username
    passwordKey: password
---
apiVersion: v1
kind: Secret
metadata:
  name: kubepost-instance-credentials
data:
  username: cG9zdGdyZXM=
  password: cm9vdA==
---
apiVersion: kubepost.io/v1alpha1
kind: Role
metadata:
  name: kubepost
  namespace: default
spec:
  roleName: kubepost
  preventDeletion: false
  instanceRef:
    name: kubepost
    namespace: default
  grant:
    database: kubepost
    objectType: database
    privileges:
      - ALL PRIVILEGES
---
apiVersion: kubepost.io/v1alpha1
kind: Database
metadata:
  name: kubepost
  namespace: default
spec:
  databaseName: kubepost
  preventDeletion: false
  instanceRef:
    name: kubepost
    namespace: default
  extensions:
    - name: pg_stat_statements
      version: "1.8"
    - name: postgres_fdw
---
