apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ddns-updater

resources:
  - postgres.yaml
  - kubepost-instance-credentials.yaml
  - kubepost-role-credentials.yaml
  - instance.yaml
  - role.yaml
  - database.yaml
