apiVersion: kubepost.io/v1alpha1
kind: Role
metadata:
  name: kubepost
spec:
  roleName: kubepost
  preventDeletion: false
  passwordRef:
    name: kubepost-role-credentials
    passwordKey: password
  instanceRef:
    name: kubepost
  options:
    - SUPERUSER
    - LOGIN
  groups:
    - name: kubepost-admin
      withAdminOption: true
