# permissions for end users to edit databases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: database-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubepost
    app.kubernetes.io/part-of: kubepost
    app.kubernetes.io/managed-by: kustomize
  name: database-editor-role
rules:
- apiGroups:
  - postgres.kubepost.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.kubepost.io
  resources:
  - databases/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: database-editor-rolebinding
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: database-editor-role
