name: image

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compute docker tag
        id: compute_tag
        run: |
          if [[ $GITHUB_REF_TYPE == "tag" ]]; then
            TAG="$(echo $GITHUB_REF_NAME | sed 's/[^a-zA-Z0-9_.-]/-/g' | sed -e 's/^v//')"
          else
            TAG="${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$(git rev-parse --short HEAD)"
          fi
          echo "computed docker tag: $TAG"
          echo '::set-output name=tag::'${TAG}

      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set up qemu
        uses: docker/setup-qemu-action@v1

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{inputs.push}}
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ steps.compute_tag.outputs.tag }}
