name: release

on:
  push:
    tags:
      - "v*"

jobs:
  quality:
    uses: ./.github/workflows/quality.yaml

  manifest:
    uses: ./.github/workflows/manifest.yaml

  image:
    needs: [ quality ]
    uses: ./.github/workflows/image.yaml
    with:
      push: true

  release:
    runs-on: ubuntu-latest
    needs: [ manifest, image ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: manifests
          path: ${{ github.workspace }}/build/config

      - name: release yaml manifests
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/build/config/bundle.yaml
