name: docker

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: orbatschow/kubepost:latest
      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}